pub mod app;
pub mod raw;
pub mod raw_ext;
pub mod unix;
pub mod argon2_scrypt;
pub mod bcrypt_;
pub mod detector;

use std::fmt::Display;

use serde::{Serialize, Deserialize};

/// A single hash entry with its metadata and crack status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashEntry {
    /// The raw hash string as read from the input file.
    pub raw: String,
    /// The detected hash type.
    pub hash_type: HashType,
    /// Decoded bytes of the hash portion (excluding prefix/salt).
    pub hash_bytes: Vec<u8>,
    /// Optional salt extracted from the hash string.
    pub salt: Option<String>,
    /// Optional username extracted from format `user:hash`.
    pub username: Option<String>,
    /// Whether this hash has been cracked.
    pub cracked: bool,
    /// The plaintext password if cracked, or `None`.
    pub password: Option<String>,
}

/// Supported hash algorithms and format variants.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum HashType {
    /// MD5 (128-bit hex digest).
    MD5,
    /// Unix `$1$` MD5-based crypt.
    MD5Crypt,
    /// SHA-1 (160-bit hex digest).
    SHA1,
    /// SHA-224 (224-bit hex digest).
    SHA224,
    /// SHA-256 (256-bit hex digest).
    SHA256,
    /// Unix `$5$` SHA-256 crypt.
    SHA256Crypt,
    /// SHA-384 (384-bit hex digest).
    SHA384,
    /// SHA-512 (512-bit hex digest).
    SHA512,
    /// SHA-512/224 (224-bit truncated SHA-512).
    SHA512_224,
    /// SHA-512/256 (256-bit truncated SHA-512).
    SHA512_256,
    /// Unix `$6$` SHA-512 crypt.
    SHA512Crypt,
    /// SHA3-224 (224-bit hex digest).
    SHA3224,
    /// SHA3-256 (256-bit hex digest).
    SHA3256,
    /// SHA3-384 (384-bit hex digest).
    SHA3384,
    /// SHA3-512 (512-bit hex digest).
    SHA3512,
    /// BLAKE2b-256 (256-bit hex digest).
    BLAKE2B256,
    /// BLAKE2s-256 (256-bit hex digest, 32-bit variant).
    BLAKE2S256,
    /// BLAKE2b-512 (512-bit hex digest).
    BLAKE2B512,
    /// RIPEMD-128 (128-bit hex digest).
    RIPEMD128,
    /// RIPEMD-160 (160-bit hex digest).
    RIPEMD160,
    /// RIPEMD-256 (256-bit hex digest).
    RIPEMD256,
    /// RIPEMD-320 (320-bit hex digest).
    RIPEMD320,
    /// MD2 (128-bit hex digest).
    MD2,
    /// MD4 (128-bit hex digest).
    MD4,
    /// Whirlpool (512-bit hex digest).
    WHIRLPOOL,
    /// Streebog (GOST R 34.11-2012) 256-bit hex digest.
    STREEBOG256,
    /// Streebog (GOST R 34.11-2012) 512-bit hex digest.
    STREEBOG512,
    /// Tiger-192 (192-bit hex digest).
    TIGER192,
    /// JH-224 (224-bit hex digest).
    JH224,
    /// JH-256 (256-bit hex digest).
    JH256,
    /// JH-384 (384-bit hex digest).
    JH384,
    /// JH-512 (512-bit hex digest).
    JH512,
    /// Skein-256 (256-bit hex digest).
    SKEIN256,
    /// Skein-512 (512-bit hex digest).
    SKEIN512,
    /// Shabal-192 (192-bit hex digest).
    SHABAL192,
    /// Shabal-224 (224-bit hex digest).
    SHABAL224,
    /// Shabal-256 (256-bit hex digest).
    SHABAL256,
    /// Shabal-384 (384-bit hex digest).
    SHABAL384,
    /// Shabal-512 (512-bit hex digest).
    SHABAL512,
    /// GOST R 34.11-94 256-bit hex digest.
    GOST94256,
    /// GOST R 34.11-94 512-bit hex digest.
    GOST94512,
    /// BLAKE2b-384 (384-bit hex digest).
    BLAKE2B384,
    /// BLAKE2b-224 (224-bit hex digest).
    BLAKE2B224,
    /// BLAKE2b-160 (160-bit hex digest).
    BLAKE2B160,
    /// BLAKE2s-128 (128-bit hex digest).
    BLAKE2S128,
    /// BLAKE2s-160 (160-bit hex digest).
    BLAKE2S160,
    /// BLAKE3-256 (256-bit hex digest).
    BLAKE3256,
    /// Apache MD5 (`$apr1$`).
    APR1MD5,
    /// PHPass / WordPress (`$P$` / `$H$`).
    PHPASS,
    /// Drupal 7 (`$S$`).
    DRUPAL7,
    /// osCommerce / xt:Commerce / AEF.
    OSCOMMERCE,
    /// PostgreSQL MD5.
    POSTGRESQL,
    /// MySQL 4.1/5.x.
    MYSQL41,
    /// Oracle 10g.
    ORACLE10G,
    /// Oracle 11g/12c.
    ORACLE11G,
    /// MSSQL 2005.
    MSSQL2005,
    /// MSSQL 2012.
    MSSQL2012,
    /// vBulletin 3.x/4.x.
    VBULLETIN3,
    /// vBulletin 5.x.
    VBULLETIN5,
    /// SMF 1.x/2.x.
    SMF,
    /// IPB 2.x / MyBB 1.x.
    IPB2,
    /// IPB 3.x+.
    IPB3,
    /// MediaWiki.
    MEDIAWIKI,
    /// Cisco PIX hash.
    CISCOPIX,
    /// Cisco Type 5 (enable secret).
    CISCO5,
    /// HMAC-SHA1.
    HMACSHA1,
    /// HMAC-SHA256.
    HMACSHA256,
    /// HMAC-MD5.
    HMACMD5,
    /// HMAC-SHA512.
    HMACSHA512,
    /// HMAC-SHA224.
    HMACSHA224,
    /// HMAC-SHA384.
    HMACSHA384,
    /// HMAC-RIPEMD160.
    HMACRIPEMD160,
    /// PBKDF2-HMAC-SHA256.
    PBKDF2SHA256,
    /// PBKDF2-HMAC-SHA512.
    PBKDF2SHA512,
    /// PBKDF2-HMAC-SHA1.
    PBKDF2SHA1,
    /// DCC1 (Domain Cached Credentials).
    DCC1,
    /// DCC2 (Domain Cached Credentials 2).
    DCC2,
    /// NTLMv2.
    NTLMV2,
    /// Salted MD5 (MD5(password + salt)).
    SALTEDMD5,
    /// Salted SHA-1 (SHA1(password + salt)).
    SALTEDSHA1,
    /// Salted SHA-256 (SHA256(password + salt)).
    SALTEDSHA256,
    /// Salted SHA-512 (SHA512(password + salt)).
    SALTEDSHA512,
    /// Salted SHA-384 (SHA384(password + salt)).
    SALTEDSHA384,
    /// Double MD5 (MD5(MD5(password))).
    DOUBLEMD5,
    /// Double SHA-1 (SHA1(SHA1(password))).
    DOUBLESHA1,
    /// Double SHA-256 (SHA256(SHA256(password))).
    DOUBLESHA256,
    /// {SHA} base64-encoded SHA-1.
    SHA1DASH,
    /// LDAP SSHA1 (Salted SHA1 in base64).
    SSHA1,
    /// LDAP SSHA256 (Salted SHA256 in base64).
    SSHA256,
    /// HMAC-SHA512/224.
    HMACSHA512_224,
    /// HMAC-SHA512/256.
    HMACSHA512_256,
    /// HMAC-SHA3-224.
    HMACSHA3224,
    /// HMAC-SHA3-256.
    HMACSHA3256,
    /// HMAC-SHA3-384.
    HMACSHA3384,
    /// HMAC-SHA3-512.
    HMACSHA3512,
    /// HMAC-BLAKE2b-256.
    HMACBLAKE2B256,
    /// HMAC-BLAKE2s-256.
    HMACBLAKE2S256,
    /// HMAC-BLAKE2b-512.
    HMACBLAKE2B512,
    /// HMAC-RIPEMD128.
    HMACRIPEMD128,
    /// HMAC-RIPEMD256.
    HMACRIPEMD256,
    /// HMAC-RIPEMD320.
    HMACRIPEMD320,
    /// HMAC-Whirlpool.
    HMACWHIRLPOOL,
    /// HMAC-Streebog-256.
    HMACSTREEBOG256,
    /// HMAC-Streebog-512.
    HMACSTREEBOG512,
    /// PBKDF2-SHA384.
    PBKDF2SHA384,
    /// PBKDF2-HMAC-SHA224.
    PBKDF2SHA224,
    /// Salted SHA-224 (SHA224(password + salt)).
    SALTEDSHA224,
    /// Triple MD5 (MD5(MD5(MD5(password)))).
    TRIPLEMD5,
    /// MD5 Half (first 16 hex chars of MD5).
    MD5HALF,
    /// CRC-8/ITU.
    CRC8ITU,
    /// CRC-16/CCITT.
    CRC16CCITT,
    /// CRC-16/MODBUS.
    CRC16MODBUS,
    /// CRC-32/BZIP2.
    CRC32BZIP2,
    /// CRC-32/MPEG2.
    CRC32MPEG2,
    /// CRC-64/ECMA-182.
    CRC64ECMA,
    /// NTLMv1 (NetNTLMv1 challenge/response).
    NTLMV1,
    /// CRAM-MD5 (mail auth digest).
    CRAMMD5,
    /// PLAINTEXT / identity hash.
    PLAINTEXT,
    /// CRC-24 (OpenPGP).
    CRC24,
    /// MySQL 3.21 (OLD_PASSWORD).
    MYSQL321,
    /// Oracle 7 (DES-based old hash).
    ORACLE7,
    /// Snefru-128.
    SNEFRU128,
    /// Snefru-256.
    SNEFRU256,
    /// Salted SHA3-256.
    SALTEDSHA3256,
    /// Salted SHA3-512.
    SALTEDSHA3512,
    /// HMAC-GOST94.
    HMACGOST94,
    /// HMAC-Tiger.
    HMACTIGER,
    /// CRC8 checksum.
    CRC8,
    /// CRC16 checksum.
    CRC16,
    /// CRC32C (Castagnoli) checksum.
    CRC32C,
    /// CRC32 checksum.
    CRC32,
    /// CRC64 checksum.
    CRC64,
    /// Adler-32 checksum.
    ADLER32,
    /// macOS 10.8+ PBKDF2.
    MACOSPBKDF2,
    /// Sun MD5 Crypt (`$md5$`).
    SUNMD5,
    /// BSDi Crypt (`_`).
    BSDICRYPT,
    /// NTLM (MD4-based Windows NT hash, 128-bit hex).
    NTLM,
    /// LM (DES-based LAN Manager hash).
    LM,
    /// bcrypt `$2b$` / `$2y$` variant.
    BCrypt,
    /// bcrypt `$2a$` variant.
    BCryptA,
    /// Argon2i (data-independent memory-hard hash).
    Argon2i,
    /// Argon2d (data-dependent memory-hard hash).
    Argon2d,
    /// Argon2id (hybrid memory-hard hash).
    Argon2id,
    /// scrypt (memory-hard key-derivation function).
    Scrypt,
    /// LM CHAPv2 (MS-CHAPv2 challenge/response).
    LMCHAPV2,
    /// Domain Cached Credentials v3.
    DCC3,
    /// SAP CODVN B (BCODE).
    SAPCODVNB,
    /// SAP CODVN F/G (PASSCODE).
    SAPCODVNFG,
    /// EPiServer (EPi).
    EPI,
    /// PunBB forum hash.
    PUNBB,
    /// Novell LDAP SHA1.
    NSLDAP,
    /// Lotus Notes / Domino.
    LOTUSNOTES,
    /// CRAM-MD5 challenge alternate format.
    CHALLENGE,
    /// GOST R 34.11-94 HMAC version (Test S-box).
    GOST94HMAC,
    /// HMAC-BLAKE2b-224.
    HMACBLAKE2B224,
    /// HMAC-BLAKE2b-384.
    HMACBLAKE2B384,
    /// SHA-256 Crypt with $rounds= prefix.
    SHA256CRYPTROUNDS,
    /// HMAC-SHA1 with username prefix format.
    HMACSHA1USER,
    /// SKIP32 (Skipjack 32-bit checksum).
    SKIP32,
    /// xxHash32.
    XXHASH32,

    // ── Standard Algorithms ──
    SM3,
    HAS160,
    Groestl224,
    Groestl256,
    Groestl384,
    Groestl512,
    BMW224,
    BMW256,
    BMW384,
    BMW512,
    Echo224,
    Echo256,
    Echo384,
    Echo512,
    Shavite2224,
    Shavite2256,
    Shavite2384,
    Shavite2512,
    SIMD224,
    SIMD256,
    SIMD384,
    SIMD512,
    Luffa224,
    Luffa256,
    Luffa384,
    Luffa512,
    CubeHash224,
    CubeHash256,
    CubeHash384,
    CubeHash512,
    Fugue224,
    Fugue256,
    Fugue384,
    Fugue512,
    Hamsi224,
    Hamsi256,
    Hamsi384,
    Hamsi512,
    Panama128,
    RadioGatun32,
    RadioGatun64,
    Haval128,
    Haval160,
    Haval192,
    Haval224,
    Haval256,
    FSB160,
    FSB224,
    FSB256,
    FSB384,
    FSB512,
    ECOH128,
    ECOH192,
    ECOH256,

    // ── More CRC & Checksums ──
    CRC10,
    CRC11,
    CRC12,
    CRC13,
    CRC14,
    CRC15,
    CRC17,
    CRC21,
    CRC24C,
    CRC30,
    CRC31,
    CRC40,
    CRC82,
    CRCDNP,
    CRCJAM,
    Fletcher4,
    Fletcher8,
    Fletcher16,
    Fletcher32,
    XOR8,
    Sum8,
    Sum16,
    Sum24,
    Sum32,
    Sum64,

    // ── Application / CMS / Framework ──
    DjangoMD5,
    DjangoSHA256,
    DjangoPBKDF2,
    JoomlaMD5,
    JoomlaSHA256,
    Drupal8,
    XenForo,
    Woltlab,
    MyBBHash,
    Vanilla,
    FluxBB,
    CakePHP,
    CodeIgniter,
    LaravelBCrypt,
    Magento,
    MODX,
    Moodle,
    PrestaShop,
    TYPO3,
    Umbraco,
    WHMCS,
    Zikula,
    Elgg,
    WordPressPHPass,
    PHPHash,

    // ── Enterprise & Database ──
    Oracle8,
    Oracle9,
    Oracle12c,
    IBMDB2,
    Progress,
    Sybase,
    Teradata,
    MSSQL2000,
    MSSQL2008,
    MSSQL2017,
    MySQL5,
    MySQL8,
    PostgreSQLSCRAM,
    MongoDB,
    Redis,
    RavenDB,
    CouchDB,
    CiscoType7,
    Juniper,
    Huawei,
    Nokia,
    Alcatel,
    ZTE,
    Ericsson,
    SNMP,
    RADIUSCHAP,
    Kerberos5,
    AFS,
    DPAPI,
    BitLocker,
    TrueCrypt,
    FileVault,
    LUKS,
    VeraCrypt,
    WindowsHello,

    // ── Blockchain & Crypto ──
    X11,
    X13,
    X15,
    X17,
    Quark,
    Neoscrypt,
    Lyra2RE,
    Yescrypt,
    ScryptN,
    ScryptJ,
    Bitcoin,
    Ethereum,
    Litecoin,
    Dogecoin,
    Ripple,
    Monero,
    Dash,
    Zcash,
    Namecoin,
    Peercoin,

    // ── Legacy & Unix ──
    DESCrypt,
    BSDAuth,
    MD5CryptAPR,
    BlowfishOpenBSD,
    LinuxOverflow,
    UnixOld,
    DESBSDi,
    HPManaged,
    SNEFRU128Legacy,
    HMACSHA256_128,
    HMACSHA1_96,
    GPG,
    PGPS2K,
    LotusNotes5,
    MSSQLOld,
    MySQLOld1,
    PostgreSQLSCRAMSHA256,
    FreeRADIUSMD5,
    OpenVPNMD5,
    DigestMD5,
    AWS4HMACSHA256,
    EthereumWallet,
    RippleWallet,
    Stellar,
    Cardano,
    Polkadot,
    Solana,
    WPAPBKDF2,
    WPA2PMKID,
    WPA3SAE,
    iSCSI_CHAP,
    PythonMD5,
    RabbitMQMD5,
    RedisMD5,

    /// Unrecognized or unsupported hash format.
    Unknown,
}

impl HashType {
    /// Returns a human-readable display name for this hash type.
    pub fn name(&self) -> &'static str {
        match self {
            HashType::MD5 => "MD5",
            HashType::MD5Crypt => "MD5 Crypt",
            HashType::SHA1 => "SHA-1",
            HashType::SHA224 => "SHA-224",
            HashType::SHA256 => "SHA-256",
            HashType::SHA256Crypt => "SHA-256 Crypt",
            HashType::SHA384 => "SHA-384",
            HashType::SHA512 => "SHA-512",
            HashType::SHA512_224 => "SHA-512/224",
            HashType::SHA512_256 => "SHA-512/256",
            HashType::SHA512Crypt => "SHA-512 Crypt",
            HashType::SHA3224 => "SHA3-224",
            HashType::SHA3256 => "SHA3-256",
            HashType::SHA3384 => "SHA3-384",
            HashType::SHA3512 => "SHA3-512",
            HashType::BLAKE2B256 => "BLAKE2b-256",
            HashType::BLAKE2S256 => "BLAKE2s-256",
            HashType::BLAKE2B512 => "BLAKE2b-512",
            HashType::RIPEMD128 => "RIPEMD-128",
            HashType::RIPEMD160 => "RIPEMD-160",
            HashType::RIPEMD256 => "RIPEMD-256",
            HashType::RIPEMD320 => "RIPEMD-320",
            HashType::MD2 => "MD2",
            HashType::MD4 => "MD4",
            HashType::WHIRLPOOL => "Whirlpool",
            HashType::STREEBOG256 => "Streebog-256",
            HashType::STREEBOG512 => "Streebog-512",
            HashType::TIGER192 => "Tiger-192",
            HashType::JH224 => "JH-224",
            HashType::JH256 => "JH-256",
            HashType::JH384 => "JH-384",
            HashType::JH512 => "JH-512",
            HashType::SKEIN256 => "Skein-256",
            HashType::SKEIN512 => "Skein-512",
            HashType::SHABAL192 => "Shabal-192",
            HashType::SHABAL224 => "Shabal-224",
            HashType::SHABAL256 => "Shabal-256",
            HashType::SHABAL384 => "Shabal-384",
            HashType::SHABAL512 => "Shabal-512",
            HashType::GOST94256 => "GOST94-256",
            HashType::GOST94512 => "GOST94-512",
            HashType::BLAKE2B384 => "BLAKE2b-384",
            HashType::BLAKE2B224 => "BLAKE2b-224",
            HashType::BLAKE2B160 => "BLAKE2b-160",
            HashType::BLAKE2S128 => "BLAKE2s-128",
            HashType::BLAKE2S160 => "BLAKE2s-160",
            HashType::BLAKE3256 => "BLAKE3-256",
            HashType::APR1MD5 => "Apache MD5",
            HashType::PHPASS => "PHPass",
            HashType::DRUPAL7 => "Drupal 7",
            HashType::OSCOMMERCE => "osCommerce",
            HashType::POSTGRESQL => "PostgreSQL MD5",
            HashType::MYSQL41 => "MySQL 4.1/5.x",
            HashType::ORACLE10G => "Oracle 10g",
            HashType::ORACLE11G => "Oracle 11g/12c",
            HashType::MSSQL2005 => "MSSQL 2005",
            HashType::MSSQL2012 => "MSSQL 2012",
            HashType::VBULLETIN3 => "vBulletin 3/4",
            HashType::VBULLETIN5 => "vBulletin 5",
            HashType::SMF => "SMF 1/2",
            HashType::IPB2 => "IPB 2 / MyBB",
            HashType::IPB3 => "IPB 3+",
            HashType::MEDIAWIKI => "MediaWiki",
            HashType::CISCOPIX => "Cisco PIX",
            HashType::CISCO5 => "Cisco Type 5",
            HashType::HMACSHA1 => "HMAC-SHA1",
            HashType::HMACSHA256 => "HMAC-SHA256",
            HashType::HMACMD5 => "HMAC-MD5",
            HashType::HMACSHA512 => "HMAC-SHA512",
            HashType::HMACSHA224 => "HMAC-SHA224",
            HashType::HMACSHA384 => "HMAC-SHA384",
            HashType::HMACRIPEMD160 => "HMAC-RIPEMD160",
            HashType::PBKDF2SHA256 => "PBKDF2-SHA256",
            HashType::PBKDF2SHA512 => "PBKDF2-SHA512",
            HashType::PBKDF2SHA1 => "PBKDF2-SHA1",
            HashType::DCC1 => "DCC1",
            HashType::DCC2 => "DCC2",
            HashType::NTLMV2 => "NTLMv2",
            HashType::SALTEDMD5 => "Salted MD5",
            HashType::SALTEDSHA1 => "Salted SHA-1",
            HashType::SALTEDSHA256 => "Salted SHA-256",
            HashType::SALTEDSHA512 => "Salted SHA-512",
            HashType::SALTEDSHA384 => "Salted SHA-384",
            HashType::DOUBLEMD5 => "Double MD5",
            HashType::DOUBLESHA1 => "Double SHA-1",
            HashType::DOUBLESHA256 => "Double SHA-256",
            HashType::SHA1DASH => "{SHA}",
            HashType::SSHA1 => "SSHA-1",
            HashType::SSHA256 => "SSHA-256",
            HashType::HMACSHA512_224 => "HMAC-SHA512/224",
            HashType::HMACSHA512_256 => "HMAC-SHA512/256",
            HashType::HMACSHA3224 => "HMAC-SHA3-224",
            HashType::HMACSHA3256 => "HMAC-SHA3-256",
            HashType::HMACSHA3384 => "HMAC-SHA3-384",
            HashType::HMACSHA3512 => "HMAC-SHA3-512",
            HashType::HMACBLAKE2B256 => "HMAC-BLAKE2b-256",
            HashType::HMACBLAKE2S256 => "HMAC-BLAKE2s-256",
            HashType::HMACBLAKE2B512 => "HMAC-BLAKE2b-512",
            HashType::HMACRIPEMD128 => "HMAC-RIPEMD128",
            HashType::HMACRIPEMD256 => "HMAC-RIPEMD256",
            HashType::HMACRIPEMD320 => "HMAC-RIPEMD320",
            HashType::HMACWHIRLPOOL => "HMAC-Whirlpool",
            HashType::HMACSTREEBOG256 => "HMAC-Streebog-256",
            HashType::HMACSTREEBOG512 => "HMAC-Streebog-512",
            HashType::PBKDF2SHA384 => "PBKDF2-SHA384",
            HashType::PBKDF2SHA224 => "PBKDF2-SHA224",
            HashType::SALTEDSHA224 => "Salted SHA-224",
            HashType::TRIPLEMD5 => "Triple MD5",
            HashType::MD5HALF => "MD5 Half",
            HashType::CRC8ITU => "CRC-8/ITU",
            HashType::CRC16CCITT => "CRC-16/CCITT",
            HashType::CRC16MODBUS => "CRC-16/MODBUS",
            HashType::CRC32BZIP2 => "CRC-32/BZIP2",
            HashType::CRC32MPEG2 => "CRC-32/MPEG-2",
            HashType::CRC64ECMA => "CRC-64/ECMA-182",
            HashType::NTLMV1 => "NTLMv1",
            HashType::CRAMMD5 => "CRAM-MD5",
            HashType::PLAINTEXT => "PLAINTEXT",
            HashType::CRC24 => "CRC-24",
            HashType::MYSQL321 => "MySQL 3.21",
            HashType::ORACLE7 => "Oracle 7",
            HashType::SNEFRU128 => "Snefru-128",
            HashType::SNEFRU256 => "Snefru-256",
            HashType::SALTEDSHA3256 => "Salted SHA3-256",
            HashType::SALTEDSHA3512 => "Salted SHA3-512",
            HashType::HMACGOST94 => "HMAC-GOST94",
            HashType::HMACTIGER => "HMAC-Tiger",
            HashType::CRC8 => "CRC8",
            HashType::CRC16 => "CRC16",
            HashType::CRC32C => "CRC32C",
            HashType::ADLER32 => "Adler-32",
            HashType::CRC32 => "CRC32",
            HashType::CRC64 => "CRC64",
            HashType::MACOSPBKDF2 => "macOS PBKDF2",
            HashType::SUNMD5 => "Sun MD5",
            HashType::BSDICRYPT => "BSDi Crypt",
            HashType::NTLM => "NTLM",
            HashType::LM => "LM",
            HashType::BCrypt => "bcrypt",
            HashType::BCryptA => "bcrypt ($2a$)",
            HashType::Argon2i => "Argon2i",
            HashType::Argon2d => "Argon2d",
            HashType::Argon2id => "Argon2id",
            HashType::Scrypt => "scrypt",
            HashType::LMCHAPV2 => "LM CHAPv2",
            HashType::DCC3 => "DCC3",
            HashType::SAPCODVNB => "SAP CODVN B",
            HashType::SAPCODVNFG => "SAP CODVN F/G",
            HashType::EPI => "EPi",
            HashType::PUNBB => "PunBB",
            HashType::NSLDAP => "NSLDAP",
            HashType::LOTUSNOTES => "Lotus Notes",
            HashType::CHALLENGE => "Challenge",
            HashType::GOST94HMAC => "GOST94 HMAC",
            HashType::HMACBLAKE2B224 => "HMAC-BLAKE2b-224",
            HashType::HMACBLAKE2B384 => "HMAC-BLAKE2b-384",
            HashType::SHA256CRYPTROUNDS => "SHA-256 Crypt ($rounds$)",
            HashType::HMACSHA1USER => "HMAC-SHA1 (username)",
            HashType::SKIP32 => "SKIP32",
            HashType::XXHASH32 => "xxHash32",
            HashType::SM3 => "SM3",
            HashType::HAS160 => "HAS-160",
            HashType::Groestl224 => "Groestl-224",
            HashType::Groestl256 => "Groestl-256",
            HashType::Groestl384 => "Groestl-384",
            HashType::Groestl512 => "Groestl-512",
            HashType::BMW224 => "BMW-224",
            HashType::BMW256 => "BMW-256",
            HashType::BMW384 => "BMW-384",
            HashType::BMW512 => "BMW-512",
            HashType::Echo224 => "Echo-224",
            HashType::Echo256 => "Echo-256",
            HashType::Echo384 => "Echo-384",
            HashType::Echo512 => "Echo-512",
            HashType::Shavite2224 => "SHAvite-3-224",
            HashType::Shavite2256 => "SHAvite-3-256",
            HashType::Shavite2384 => "SHAvite-3-384",
            HashType::Shavite2512 => "SHAvite-3-512",
            HashType::SIMD224 => "SIMD-224",
            HashType::SIMD256 => "SIMD-256",
            HashType::SIMD384 => "SIMD-384",
            HashType::SIMD512 => "SIMD-512",
            HashType::Luffa224 => "Luffa-224",
            HashType::Luffa256 => "Luffa-256",
            HashType::Luffa384 => "Luffa-384",
            HashType::Luffa512 => "Luffa-512",
            HashType::CubeHash224 => "CubeHash-224",
            HashType::CubeHash256 => "CubeHash-256",
            HashType::CubeHash384 => "CubeHash-384",
            HashType::CubeHash512 => "CubeHash-512",
            HashType::Fugue224 => "Fugue-224",
            HashType::Fugue256 => "Fugue-256",
            HashType::Fugue384 => "Fugue-384",
            HashType::Fugue512 => "Fugue-512",
            HashType::Hamsi224 => "Hamsi-224",
            HashType::Hamsi256 => "Hamsi-256",
            HashType::Hamsi384 => "Hamsi-384",
            HashType::Hamsi512 => "Hamsi-512",
            HashType::Panama128 => "Panama-128",
            HashType::RadioGatun32 => "RadioGatún-32",
            HashType::RadioGatun64 => "RadioGatún-64",
            HashType::Haval128 => "Haval-128",
            HashType::Haval160 => "Haval-160",
            HashType::Haval192 => "Haval-192",
            HashType::Haval224 => "Haval-224",
            HashType::Haval256 => "Haval-256",
            HashType::FSB160 => "FSB-160",
            HashType::FSB224 => "FSB-224",
            HashType::FSB256 => "FSB-256",
            HashType::FSB384 => "FSB-384",
            HashType::FSB512 => "FSB-512",
            HashType::ECOH128 => "ECOH-128",
            HashType::ECOH192 => "ECOH-192",
            HashType::ECOH256 => "ECOH-256",
            HashType::CRC10 => "CRC-10",
            HashType::CRC11 => "CRC-11",
            HashType::CRC12 => "CRC-12",
            HashType::CRC13 => "CRC-13",
            HashType::CRC14 => "CRC-14",
            HashType::CRC15 => "CRC-15",
            HashType::CRC17 => "CRC-17",
            HashType::CRC21 => "CRC-21",
            HashType::CRC24C => "CRC-24C",
            HashType::CRC30 => "CRC-30",
            HashType::CRC31 => "CRC-31",
            HashType::CRC40 => "CRC-40",
            HashType::CRC82 => "CRC-82",
            HashType::CRCDNP => "CRC-DNP",
            HashType::CRCJAM => "CRC-JAM",
            HashType::Fletcher4 => "Fletcher-4",
            HashType::Fletcher8 => "Fletcher-8",
            HashType::Fletcher16 => "Fletcher-16",
            HashType::Fletcher32 => "Fletcher-32",
            HashType::XOR8 => "XOR-8",
            HashType::Sum8 => "Sum-8",
            HashType::Sum16 => "Sum-16",
            HashType::Sum24 => "Sum-24",
            HashType::Sum32 => "Sum-32",
            HashType::Sum64 => "Sum-64",
            HashType::DjangoMD5 => "Django MD5",
            HashType::DjangoSHA256 => "Django SHA-256",
            HashType::DjangoPBKDF2 => "Django PBKDF2",
            HashType::JoomlaMD5 => "Joomla MD5",
            HashType::JoomlaSHA256 => "Joomla SHA-256",
            HashType::Drupal8 => "Drupal 8",
            HashType::XenForo => "XenForo",
            HashType::Woltlab => "Woltlab",
            HashType::MyBBHash => "MyBB 1.x",
            HashType::Vanilla => "Vanilla",
            HashType::FluxBB => "FluxBB",
            HashType::CakePHP => "CakePHP",
            HashType::CodeIgniter => "CodeIgniter",
            HashType::LaravelBCrypt => "Laravel bcrypt",
            HashType::Magento => "Magento",
            HashType::MODX => "MODX",
            HashType::Moodle => "Moodle",
            HashType::PrestaShop => "PrestaShop",
            HashType::TYPO3 => "TYPO3",
            HashType::Umbraco => "Umbraco",
            HashType::WHMCS => "WHMCS",
            HashType::Zikula => "Zikula",
            HashType::Elgg => "Elgg",
            HashType::WordPressPHPass => "WordPress PHPass",
            HashType::PHPHash => "PHP Hash",
            HashType::Oracle8 => "Oracle 8",
            HashType::Oracle9 => "Oracle 9",
            HashType::Oracle12c => "Oracle 12c",
            HashType::IBMDB2 => "IBM DB2",
            HashType::Progress => "Progress",
            HashType::Sybase => "Sybase",
            HashType::Teradata => "Teradata",
            HashType::MSSQL2000 => "MSSQL 2000",
            HashType::MSSQL2008 => "MSSQL 2008",
            HashType::MSSQL2017 => "MSSQL 2017",
            HashType::MySQL5 => "MySQL 5",
            HashType::MySQL8 => "MySQL 8",
            HashType::PostgreSQLSCRAM => "PostgreSQL SCRAM",
            HashType::MongoDB => "MongoDB",
            HashType::Redis => "Redis",
            HashType::RavenDB => "RavenDB",
            HashType::CouchDB => "CouchDB",
            HashType::CiscoType7 => "Cisco Type 7",
            HashType::Juniper => "Juniper",
            HashType::Huawei => "Huawei",
            HashType::Nokia => "Nokia",
            HashType::Alcatel => "Alcatel",
            HashType::ZTE => "ZTE",
            HashType::Ericsson => "Ericsson",
            HashType::SNMP => "SNMP",
            HashType::RADIUSCHAP => "RADIUS CHAP",
            HashType::Kerberos5 => "Kerberos 5",
            HashType::AFS => "AFS",
            HashType::DPAPI => "DPAPI",
            HashType::BitLocker => "BitLocker",
            HashType::TrueCrypt => "TrueCrypt",
            HashType::FileVault => "FileVault",
            HashType::LUKS => "LUKS",
            HashType::VeraCrypt => "VeraCrypt",
            HashType::WindowsHello => "Windows Hello",
            HashType::X11 => "X11",
            HashType::X13 => "X13",
            HashType::X15 => "X15",
            HashType::X17 => "X17",
            HashType::Quark => "Quark",
            HashType::Neoscrypt => "NeoScrypt",
            HashType::Lyra2RE => "Lyra2RE",
            HashType::Yescrypt => "yescrypt",
            HashType::ScryptN => "scrypt-N",
            HashType::ScryptJ => "scrypt-J",
            HashType::Bitcoin => "Bitcoin",
            HashType::Ethereum => "Ethereum",
            HashType::Litecoin => "Litecoin",
            HashType::Dogecoin => "Dogecoin",
            HashType::Ripple => "Ripple",
            HashType::Monero => "Monero",
            HashType::Dash => "Dash",
            HashType::Zcash => "Zcash",
            HashType::Namecoin => "Namecoin",
            HashType::Peercoin => "Peercoin",
            HashType::DESCrypt => "DES Crypt",
            HashType::BSDAuth => "BSD Auth",
            HashType::MD5CryptAPR => "MD5 Crypt APR",
            HashType::BlowfishOpenBSD => "Blowfish OpenBSD",
            HashType::LinuxOverflow => "Linux Overflow",
            HashType::UnixOld => "Unix Old",
            HashType::DESBSDi => "DES BSDi",
            HashType::HPManaged => "HP Managed",
            HashType::SNEFRU128Legacy => "SNEFRU-128 Legacy",
            HashType::HMACSHA256_128 => "HMAC-SHA256-128",
            HashType::HMACSHA1_96 => "HMAC-SHA1-96",
            HashType::GPG => "GPG",
            HashType::PGPS2K => "PGP S2K",
            HashType::LotusNotes5 => "Lotus Notes 5",
            HashType::MSSQLOld => "MSSQL Old",
            HashType::MySQLOld1 => "MySQL Old",
            HashType::PostgreSQLSCRAMSHA256 => "PostgreSQL SCRAM-SHA-256",
            HashType::FreeRADIUSMD5 => "FreeRADIUS MD5",
            HashType::OpenVPNMD5 => "OpenVPN MD5",
            HashType::DigestMD5 => "Digest-MD5",
            HashType::AWS4HMACSHA256 => "AWS4-HMAC-SHA256",
            HashType::EthereumWallet => "Ethereum Wallet",
            HashType::RippleWallet => "Ripple Wallet",
            HashType::Stellar => "Stellar",
            HashType::Cardano => "Cardano",
            HashType::Polkadot => "Polkadot",
            HashType::Solana => "Solana",
            HashType::WPAPBKDF2 => "WPA PBKDF2",
            HashType::WPA2PMKID => "WPA2 PMKID",
            HashType::WPA3SAE => "WPA3 SAE",
            HashType::iSCSI_CHAP => "iSCSI CHAP",
            HashType::PythonMD5 => "Python MD5",
            HashType::RabbitMQMD5 => "RabbitMQ MD5",
            HashType::RedisMD5 => "Redis MD5",
            HashType::Unknown => "Unknown",
        }
    }

    /// Returns the bit length of the hash output, if applicable.
    pub fn bit_length(&self) -> Option<usize> {
        match self {
            HashType::MD5 => Some(128),
            HashType::SHA1 => Some(160),
            HashType::SHA224 => Some(224),
            HashType::SHA256 => Some(256),
            HashType::SHA384 => Some(384),
            HashType::SHA512 => Some(512),
            HashType::SHA512_224 => Some(224),
            HashType::SHA512_256 => Some(256),
            HashType::SHA3224 => Some(224),
            HashType::SHA3256 => Some(256),
            HashType::SHA3384 => Some(384),
            HashType::SHA3512 => Some(512),
            HashType::BLAKE2B256 => Some(256),
            HashType::BLAKE2S256 => Some(256),
            HashType::BLAKE2B512 => Some(512),
            HashType::RIPEMD128 => Some(128),
            HashType::RIPEMD160 => Some(160),
            HashType::RIPEMD256 => Some(256),
            HashType::RIPEMD320 => Some(320),
            HashType::MD2 => Some(128),
            HashType::MD4 => Some(128),
            HashType::WHIRLPOOL => Some(512),
            HashType::STREEBOG256 => Some(256),
            HashType::STREEBOG512 => Some(512),
            HashType::TIGER192 => Some(192),
            HashType::JH224 => Some(224),
            HashType::JH256 => Some(256),
            HashType::JH384 => Some(384),
            HashType::JH512 => Some(512),
            HashType::SKEIN256 => Some(256),
            HashType::SKEIN512 => Some(512),
            HashType::SHABAL192 => Some(192),
            HashType::SHABAL224 => Some(224),
            HashType::SHABAL256 => Some(256),
            HashType::SHABAL384 => Some(384),
            HashType::SHABAL512 => Some(512),
            HashType::GOST94256 => Some(256),
            HashType::GOST94512 => Some(512),
            HashType::BLAKE2B384 => Some(384),
            HashType::BLAKE2B224 => Some(224),
            HashType::BLAKE2B160 => Some(160),
            HashType::BLAKE2S128 => Some(128),
            HashType::BLAKE2S160 => Some(160),
            HashType::BLAKE3256 => Some(256),
            HashType::HMACSHA512_224 => Some(224),
            HashType::HMACSHA512_256 => Some(256),
            HashType::HMACSHA3224 => Some(224),
            HashType::HMACSHA3256 => Some(256),
            HashType::HMACSHA3384 => Some(384),
            HashType::HMACSHA3512 => Some(512),
            HashType::HMACBLAKE2B256 => Some(256),
            HashType::HMACBLAKE2S256 => Some(256),
            HashType::HMACBLAKE2B512 => Some(512),
            HashType::HMACRIPEMD128 => Some(128),
            HashType::HMACRIPEMD256 => Some(256),
            HashType::HMACRIPEMD320 => Some(320),
            HashType::HMACWHIRLPOOL => Some(512),
            HashType::HMACSTREEBOG256 => Some(256),
            HashType::HMACSTREEBOG512 => Some(512),
            HashType::PBKDF2SHA384 => None,
            HashType::PBKDF2SHA224 => None,
            HashType::SALTEDSHA224 => Some(224),
            HashType::TRIPLEMD5 => Some(128),
            HashType::MD5HALF => Some(64),
            HashType::CRC8ITU => Some(8),
            HashType::CRC16CCITT => Some(16),
            HashType::CRC16MODBUS => Some(16),
            HashType::CRC32BZIP2 => Some(32),
            HashType::CRC32MPEG2 => Some(32),
            HashType::CRC64ECMA => Some(64),
            HashType::NTLMV1 => Some(128),
            HashType::CRAMMD5 => Some(128),
            HashType::PLAINTEXT => None,
            HashType::CRC24 => Some(24),
            HashType::MYSQL321 => Some(64),
            HashType::ORACLE7 => None,
            HashType::SNEFRU128 => Some(128),
            HashType::SNEFRU256 => Some(256),
            HashType::SALTEDSHA3256 => Some(256),
            HashType::SALTEDSHA3512 => Some(512),
            HashType::HMACGOST94 => Some(256),
            HashType::HMACTIGER => Some(192),
            HashType::CRC8 => Some(8),
            HashType::CRC16 => Some(16),
            HashType::CRC32 => Some(32),
            HashType::CRC32C => Some(32),
            HashType::ADLER32 => Some(32),
            HashType::CRC64 => Some(64),
            HashType::NTLM => Some(128),
            HashType::LM => Some(64),
            HashType::LMCHAPV2 => Some(128),
            HashType::DCC3 => Some(128),
            HashType::SAPCODVNB => None,
            HashType::SAPCODVNFG => None,
            HashType::EPI => Some(128),
            HashType::PUNBB => Some(160),
            HashType::NSLDAP => Some(160),
            HashType::LOTUSNOTES => None,
            HashType::CHALLENGE => Some(128),
            HashType::GOST94HMAC => Some(256),
            HashType::HMACBLAKE2B224 => Some(224),
            HashType::HMACBLAKE2B384 => Some(384),
            HashType::SHA256CRYPTROUNDS => Some(256),
            HashType::HMACSHA1USER => Some(160),
            HashType::SKIP32 => Some(32),
            HashType::XXHASH32 => Some(32),
            HashType::SM3 => Some(256),
            HashType::HAS160 => Some(160),
            HashType::Groestl224 => Some(224),
            HashType::Groestl256 => Some(256),
            HashType::Groestl384 => Some(384),
            HashType::Groestl512 => Some(512),
            HashType::BMW224 => Some(224),
            HashType::BMW256 => Some(256),
            HashType::BMW384 => Some(384),
            HashType::BMW512 => Some(512),
            HashType::Echo224 => Some(224),
            HashType::Echo256 => Some(256),
            HashType::Echo384 => Some(384),
            HashType::Echo512 => Some(512),
            HashType::Shavite2224 => Some(224),
            HashType::Shavite2256 => Some(256),
            HashType::Shavite2384 => Some(384),
            HashType::Shavite2512 => Some(512),
            HashType::SIMD224 => Some(224),
            HashType::SIMD256 => Some(256),
            HashType::SIMD384 => Some(384),
            HashType::SIMD512 => Some(512),
            HashType::Luffa224 => Some(224),
            HashType::Luffa256 => Some(256),
            HashType::Luffa384 => Some(384),
            HashType::Luffa512 => Some(512),
            HashType::CubeHash224 => Some(224),
            HashType::CubeHash256 => Some(256),
            HashType::CubeHash384 => Some(384),
            HashType::CubeHash512 => Some(512),
            HashType::Fugue224 => Some(224),
            HashType::Fugue256 => Some(256),
            HashType::Fugue384 => Some(384),
            HashType::Fugue512 => Some(512),
            HashType::Hamsi224 => Some(224),
            HashType::Hamsi256 => Some(256),
            HashType::Hamsi384 => Some(384),
            HashType::Hamsi512 => Some(512),
            HashType::Panama128 => Some(128),
            HashType::RadioGatun32 => Some(32),
            HashType::RadioGatun64 => Some(64),
            HashType::Haval128 => Some(128),
            HashType::Haval160 => Some(160),
            HashType::Haval192 => Some(192),
            HashType::Haval224 => Some(224),
            HashType::Haval256 => Some(256),
            HashType::FSB160 => Some(160),
            HashType::FSB224 => Some(224),
            HashType::FSB256 => Some(256),
            HashType::FSB384 => Some(384),
            HashType::FSB512 => Some(512),
            HashType::ECOH128 => Some(128),
            HashType::ECOH192 => Some(192),
            HashType::ECOH256 => Some(256),
            HashType::CRC10 => Some(10),
            HashType::CRC11 => Some(11),
            HashType::CRC12 => Some(12),
            HashType::CRC13 => Some(13),
            HashType::CRC14 => Some(14),
            HashType::CRC15 => Some(15),
            HashType::CRC17 => Some(17),
            HashType::CRC21 => Some(21),
            HashType::CRC24C => Some(24),
            HashType::CRC30 => Some(30),
            HashType::CRC31 => Some(31),
            HashType::CRC40 => Some(40),
            HashType::CRC82 => Some(82),
            HashType::CRCDNP => Some(24),
            HashType::CRCJAM => Some(32),
            HashType::Fletcher4 => Some(4),
            HashType::Fletcher8 => Some(8),
            HashType::Fletcher16 => Some(16),
            HashType::Fletcher32 => Some(32),
            HashType::XOR8 => Some(8),
            HashType::Sum8 => Some(8),
            HashType::Sum16 => Some(16),
            HashType::Sum24 => Some(24),
            HashType::Sum32 => Some(32),
            HashType::Sum64 => Some(64),
            HashType::DjangoMD5 => Some(128),
            HashType::DjangoSHA256 => Some(256),
            HashType::DjangoPBKDF2 => None,
            HashType::JoomlaMD5 => Some(128),
            HashType::JoomlaSHA256 => Some(256),
            HashType::Drupal8 => Some(256),
            HashType::XenForo => None,
            HashType::Woltlab => None,
            HashType::MyBBHash => Some(128),
            HashType::Vanilla => None,
            HashType::FluxBB => Some(128),
            HashType::CakePHP => Some(128),
            HashType::CodeIgniter => Some(128),
            HashType::LaravelBCrypt => None,
            HashType::Magento => None,
            HashType::MODX => None,
            HashType::Moodle => None,
            HashType::PrestaShop => None,
            HashType::TYPO3 => None,
            HashType::Umbraco => None,
            HashType::WHMCS => None,
            HashType::Zikula => None,
            HashType::Elgg => None,
            HashType::WordPressPHPass => Some(128),
            HashType::PHPHash => None,
            HashType::Oracle8 => Some(64),
            HashType::Oracle9 => Some(64),
            HashType::Oracle12c => Some(512),
            HashType::IBMDB2 => None,
            HashType::Progress => None,
            HashType::Sybase => None,
            HashType::Teradata => None,
            HashType::MSSQL2000 => None,
            HashType::MSSQL2008 => None,
            HashType::MSSQL2017 => None,
            HashType::MySQL5 => Some(256),
            HashType::MySQL8 => Some(256),
            HashType::PostgreSQLSCRAM => None,
            HashType::MongoDB => None,
            HashType::Redis => None,
            HashType::RavenDB => None,
            HashType::CouchDB => None,
            HashType::CiscoType7 => None,
            HashType::Juniper => None,
            HashType::Huawei => None,
            HashType::Nokia => None,
            HashType::Alcatel => None,
            HashType::ZTE => None,
            HashType::Ericsson => None,
            HashType::SNMP => None,
            HashType::RADIUSCHAP => Some(128),
            HashType::Kerberos5 => None,
            HashType::AFS => None,
            HashType::DPAPI => None,
            HashType::BitLocker => None,
            HashType::TrueCrypt => None,
            HashType::FileVault => None,
            HashType::LUKS => None,
            HashType::VeraCrypt => None,
            HashType::WindowsHello => None,
            HashType::X11 => None,
            HashType::X13 => None,
            HashType::X15 => None,
            HashType::X17 => None,
            HashType::Quark => None,
            HashType::Neoscrypt => None,
            HashType::Lyra2RE => None,
            HashType::Yescrypt => None,
            HashType::ScryptN => None,
            HashType::ScryptJ => None,
            HashType::Bitcoin => None,
            HashType::Ethereum => None,
            HashType::Litecoin => None,
            HashType::Dogecoin => None,
            HashType::Ripple => None,
            HashType::Monero => None,
            HashType::Dash => None,
            HashType::Zcash => None,
            HashType::Namecoin => None,
            HashType::Peercoin => None,
            HashType::DESCrypt => Some(64),
            HashType::BSDAuth => None,
            HashType::MD5CryptAPR => None,
            HashType::BlowfishOpenBSD => None,
            HashType::LinuxOverflow => None,
            HashType::UnixOld => Some(64),
            HashType::DESBSDi => Some(64),
            HashType::HPManaged => None,
            HashType::SNEFRU128Legacy => Some(128),
            HashType::HMACSHA256_128 => Some(128),
            HashType::HMACSHA1_96 => Some(96),
            HashType::GPG => None,
            HashType::PGPS2K => None,
            HashType::LotusNotes5 => None,
            HashType::MSSQLOld => None,
            HashType::MySQLOld1 => Some(64),
            HashType::PostgreSQLSCRAMSHA256 => Some(256),
            HashType::FreeRADIUSMD5 => Some(128),
            HashType::OpenVPNMD5 => Some(128),
            HashType::DigestMD5 => Some(128),
            HashType::AWS4HMACSHA256 => Some(256),
            HashType::EthereumWallet => None,
            HashType::RippleWallet => None,
            HashType::Stellar => None,
            HashType::Cardano => None,
            HashType::Polkadot => None,
            HashType::Solana => None,
            HashType::WPAPBKDF2 => Some(256),
            HashType::WPA2PMKID => Some(256),
            HashType::WPA3SAE => Some(256),
            HashType::iSCSI_CHAP => Some(128),
            HashType::PythonMD5 => Some(128),
            HashType::RabbitMQMD5 => Some(128),
            HashType::RedisMD5 => Some(128),
            _ => None,
        }
    }
}

impl Display for HashType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}

/// Provides hash verification against candidate passwords.
pub trait HashCracker: Send + Sync {
    /// Returns the [`HashType`] this cracker handles.
    fn hash_type(&self) -> HashType;
    /// Returns `true` if `password` matches the given hash entry.
    fn verify(&self, password: &str, hash: &HashEntry) -> bool;
    /// Returns a human-readable name for this cracker.
    fn name(&self) -> &'static str;
    /// Returns a boxed clone of this cracker.
    fn clone_box(&self) -> Box<dyn HashCracker>;
}

/// Parses raw hash strings into [`HashEntry`] values.
pub trait HashParser: Send + Sync {
    /// Parses a hash line into a [`HashEntry`], or `None` if the format is unrecognised.
    fn parse(&self, line: &str) -> Option<HashEntry>;
    /// Returns `true` if the line looks like a hash this parser understands.
    fn can_parse(&self, line: &str) -> bool;
}
